# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openinghours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closingrules',
            options={'ordering': ['start'], 'verbose_name': 'Closing Rule', 'verbose_name_plural': 'Closing Rules'},
        ),
        migrations.AlterModelOptions(
            name='openinghours',
            options={'ordering': ['company', 'weekday', 'from_hour'], 'verbose_name': 'Opening Hours', 'verbose_name_plural': 'Opening Hours'},
        ),
        migrations.AlterField(
            model_name='closingrules',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openinghours.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='closingrules',
            name='end',
            field=models.DateTimeField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='closingrules',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='closingrules',
            name='start',
            field=models.DateTimeField(verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=b'logo', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openinghours.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='from_hour',
            field=models.TimeField(verbose_name='Opening'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='to_hour',
            field=models.TimeField(verbose_name='Closing'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], verbose_name='Weekday'),
        ),
    ]
