# Generated by Django 3.0.2 on 2020-01-02 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "logo",
                    models.FileField(
                        blank=True, null=True, upload_to="logo", verbose_name="Logo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "swappable": "OPENINGHOURS_PREMISES_MODEL",
            },
        ),
        migrations.CreateModel(
            name="OpeningHours",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ],
                        verbose_name="Weekday",
                    ),
                ),
                ("from_hour", models.TimeField(verbose_name="Opening")),
                ("to_hour", models.TimeField(verbose_name="Closing")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.OPENINGHOURS_PREMISES_MODEL,
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opening Hours",
                "verbose_name_plural": "Opening Hours",
                "ordering": ["company", "weekday", "from_hour"],
            },
        ),
        migrations.CreateModel(
            name="ClosingRules",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="Start")),
                ("end", models.DateTimeField(verbose_name="End")),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="Reason"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.OPENINGHOURS_PREMISES_MODEL,
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Closing Rule",
                "verbose_name_plural": "Closing Rules",
                "ordering": ["start"],
            },
        ),
    ]
